---
title: "長期トレンドを除いた生物季節観測データの相互相関解析"
subtitle: "日本気象予報士会 東北支部　2026年3月例会"
author: "No.3682 岩渕　巧"
date: "2026-03-14"
lang: ja
format: 
  revealjs:
    theme: simple
    slide-number: true
    incremental: false
    embed-resources: false
    css: styles_slide.css
  beamer:
    aspectratio: 169
    classoption: t
    pdf-engine: lualatex
    include-in-header: header.tex
execute: 
  echo: false
  message: false
  warning: false
params:
  city: "仙台"
---
# 長期トレンドの除去
2月例会話題提供では、さくら開花などの生物季節観測同士、あるいは気温との相関関係を算出した。  
生物季節観測データ、気温には地球温暖化による長期トレンドが影響を及ぼしていると考えられることから、この長期トレンドを除去した相関関係を算出し、再検討してみることとした。  
まずは基本データ（仙台の生物季節観測データと、月毎の平均気温）は以下の通り。
```{r}
df <- readRDS("/Users/takumi/Projects/analysis-autumn_length/data/processed/df2.rds")
```

# 長期トレンド除去の方法
長期トレンドの除去方法として、以下の3つを検討した。

1. 線形トレンドの除去  
各系列に対して　$Y_i = a + b t + \epsilon_t$　の線形回帰を行い、残差を用いて相関を算出する

2. Sen's slopeの除去. 
外れ値に強いロバストな線形回帰であるSen's slopeを用いて、各系列のトレンドを除去し、残差を用いて相関を算出する

3. 多変量回帰. 
相関ではなく　$sakura = \beta_0 + \beta_1 temp_{spring} + \beta_2 year + \epsilon$　のような多変量回帰を行い、年の影響をコントロールした上で、春の気温の影響を評価する


# さくら開花と春の気温について

## 相関係数
| 方法 | さくら開花と春の気温の相関 |
|:---|---:|
| 基本相関 | -0.794|
| 線形トレンド除去後の相関 |  -0.762|
| Sen's slope除去後の相関 |  -0.741|

基本相関は-0.794で、さくらの開花と春の気温には強い負の相関があることを示している。  
線形トレンド除去後の相関は-0.762、Sen's slope除去後の相関は-0.741で、いずれも基本相関と比較してやや弱くなっているが、依然として強い負の相関が存在することを示している。

したがって、**さくらの開花は春気温の変動に強く反応している** という結論が得られる。

## 多変量回帰

Rによる出力は以下の通り。

|term        | estimate| std.error| statistic| p.value|
|:-----------|--------:|---------:|---------:|-------:|
|(Intercept) |  143.556|    42.063|     3.413|   0.001|
|春          |   -4.962|     0.445|   -11.153|   0.000|
|年          |    0.004|     0.022|     0.165|   0.869|

春の係数-4.962は、春の気温が1度上昇すると、さくらの開花が約5日早まることを示す。p=0.001 は非常に有意な結果。  
年の係数0.004は、さくらの開花が年々約0.004日遅くなっていることを示すが、p=0.869 で有意ではない。  

したがって、**さくらの開花には春気温が強く影響しており、年の影響はほとんどない** という結論が得られる。

# 夏の気温と冬の気温について

## 相関係数
| 方法 | 夏の気温と冬の気温の相関 |
|:---|---:|
| 基本相関 | 0.302|
| 線形トレンド除去後の相関 |  0.146|
| Sen's slope除去後の相関 |  0.135|

基本相関は0.302で、夏の気温と冬の気温には弱い正の相関があることを示している。線形トレンド除去後の相関は0.146、Sen's slope除去後の相関は0.135で、いずれも基本相関と比較して半減しており、基本相関の弱い相関は長期トレンドの影響によるものと考えられる。

したがって、**長期トレンド（温暖化）除去を除去すると、夏と冬の気温はほぼ独立** という結論が得られる。

## 多変量回帰

Rによる出力は以下の通り。

|term        | estimate| std.error| statistic| p.value|
|:-----------|--------:|---------:|---------:|-------:|
|(Intercept) |  -30.581|    13.317|    -2.296|   0.025|
|冬          |    0.139|     0.156|     0.890|   0.376|
|年          |    0.026|     0.007|     3.858|   0.000|

冬の係数0.139は、冬の気温が1度上昇すると、夏の気温が約0.139度上昇することを示すが、p=0.376 は有意ではない。  
年の係数0.026は、夏の気温が年々約0.026度上昇していることを示しており、p=0.000 で非常に有意である。これは温暖化のトレンドと考えられる。

したがって、**夏の気温には冬の気温の影響はなく、長期トレンド（温暖化）の影響が大きい** という結論が得られる。
